export * from './general-data.type';
export * from './material-selection-data.type';
export * from './granulometry-composition-data.type';
export * from './binder-trial-data.type';
export * from './maximum-mixture-density-data.type';
export * from './volumetric-parameters-data.type';
export * from './optimum-binder-content-data.type';
export * from './confirmation-compression-data.type';
export * from './marshall-document.type';
